### PR TITLE
IMU

### PR DESCRIPTION
**Pull request by christqoh**
Includes several improvements

Major:
- conversion of IMU messages for Cartographer 
- IMU setup instructions
- roboy_ad package README

Minor:
- dependencies in roboy_ad
- launch files in roboy_ad for one command setup and data recording
- README cleanups in src, remove setup section, all through shellscript from now

### CODE REVIEW

**Review by lennarthaller — APPROVED** [review]
Looks very good to me! 
Haven't run it.

**Review by jonas-kerber — APPROVED** [review]
worked after removing ros_comm submodule. commit was added by @christqoh

**Comment by christqoh** [comment]
able to create valid ROS-bag with latest commits

**Comment by christqoh** [comment]
latest commit enables IMU usage in cartogarpher

**Pull request merged**
