### PR TITLE
Gazebo

### PR DESCRIPTION
**Pull request by melkonyan**
Hey guys, pls review my initial implementation of a simple gazebo simulation. 
It would be cool if at least one person would try to run the following, to verify that I didn't forget any important packages: 

1. Install dependencies from README  --- sudo apt-get install libgazebo7-dev ros-kinetic-gazebo-ros-pkgs 
ros-kinetic-gazebo-ros-control ros-kinetic-gazebo-ros-controllers
2. Build and source your catkin workspace
3. Run --- roslaunch tricycle_gazebo tricycle.launch

Hopefulle you shouldn't see any error messages on the console.

### CODE REVIEW

**Comment by christqoh** [comment]
Not sure about the last package ... unable to locate ros-kinetic-gazebo-ros-controllers:
```
christoph@ubuntu:~$ sudo apt-get install ros-kinetic-gazebo-ros-controllers
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-kinetic-gazebo-ros-controllers
```

**Comment by melkonyan** [comment]
Thanks, fixed

**Comment by christqoh** [comment]
just figured that one out as well... 👍

**Comment by christqoh** [comment]
catkin builds for me (I only do `catkin build tricycle_gazebo`), source it and `roslaunch tricycle_gazebo tricycle.launch` executes until gazebo workspace is created. Then gazebo crashes after a few warnings with Segmentation fault (core dumped):
```
[ WARN] [1547468975.641181431, 0.135000000]: The default_robot_hw_sim plugin is using the Joint::SetPosition method without preserving the link velocity.
[ WARN] [1547468975.641242022, 0.135000000]: As a result, gravity will not be simulated correctly for your model.
[ WARN] [1547468975.641255853, 0.135000000]: Please set gazebo_pid parameters, switch to the VelocityJointInterface or EffortJointInterface, or upgrade to Gazebo 9.
[ WARN] [1547468975.641267578, 0.135000000]: For details, see https://github.com/ros-simulation/gazebo_ros_pkgs/issues/612
[ INFO] [1547468975.665548802, 0.157000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1547468975.794433160, 0.289000000]: Physics dynamic reconfigure ready.
[urdf_spawner-3] process has finished cleanly
log file: /home/christoph/.ros/log/0787789e-17f8-11e9-ba79-000c290ab1e9/urdf_spawner-3*.log
Segmentation fault (core dumped)
[gazebo_gui-2] process has died [pid 11134, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/christoph/.ros/log/0787789e-17f8-11e9-ba79-000c290ab1e9/gazebo_gui-2.log].
log file: /home/christoph/.ros/log/0787789e-17f8-11e9-ba79-000c290ab1e9/gazebo_gui-2*.log
```

**Comment by christqoh** [comment]
solved: this was an issue with the VM. According to this [Gazebo Forum](http://answers.gazebosim.org/question/13214/virtual-machine-not-launching-gazebo/), you mustn't have accelerated 3D graphics activated in order for Gazebo to work.

screenshot 2019-01-14 at 13 41 37

**Review by christqoh — APPROVED** [review]

**Comment by melkonyan** [comment]
Cool, thanks for checking.

**Review by jonas-kerber — COMMENTED** [review]
can confirm what @christqoh said. Implemented his changes and gazebo starts correctly without crashing

**Review by jonas-kerber — APPROVED** [review]

**Review by lennarthaller — APPROVED** [review]

**Pull request merged**
